---
# rhacm-ztp-upgrade-upgrade-setup tasks

- name: Create directories for rhacm-ztp
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ http_store_path }}/data/upgrade"
  - "{{ rhacm_install_directory }}/rhacm-ztp"
  - "{{ rhacm_install_directory }}/rhacm-ztp/upgrade"

- name: Download upgrade graphs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ http_store_path }}/data/upgrade/{{ item.name }}"
  loop:
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.9
    name: upgrade-graph_stable-4.9
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.10
    name: upgrade-graph_stable-4.10
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.11
    name: upgrade-graph_stable-4.11
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.10
    name: upgrade-graph_fast-4.10
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.11
    name: upgrade-graph_fast-4.11
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.11
    name: upgrade-graph_candidate-4.11

- name: Get list of clusters for upgrade
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get managedclusters  -l ztp-done= --no-headers -o custom-columns=NAME:'.metadata.name'
  register: ztp_done_clusters

- name: Template CGU object(s) and patch script into single file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
  - src: cgu-platform-upgrade.yml.j2
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/cgu-platform-upgrade-{{ du_upgrade_version }}.yml"
  - src: patch-cgu.sh
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/patch-cgu-{{ du_upgrade_version }}.sh"
    mode: "0744"

- name: Template the gen_checksum.sh script
  template:
    src: gen_checksum.sh
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/gen_checksum.sh"
    mode: 0744

- name: Run the generate checksum script
  shell: |
    cd {{ rhacm_install_directory }}/rhacm-ztp/upgrade
    {{ rhacm_install_directory }}/rhacm-ztp/upgrade/gen_checksum.sh

- name: Get generate checksum script output
  slurp:
    src: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/checksum-{{ du_upgrade_version }}.yaml"
  register: image_signature_data

- name: Template the du-upgrade policy
  template:
    src: du-upgrade.yaml.j2
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/du-upgrade.yaml"

- name: Enable du-upgrade in the kustomization.yaml file
  replace:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/kustomization.yaml"
    replace: "- du-upgrade.yaml"
    regexp: "# - du-upgrade.yaml"

- name: Commit and push the above changes to cnf-features-deploy
  shell: |
    cd {{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy
    git add ztp/gitops-subscriptions/argocd/cluster/ ztp/gitops-subscriptions/argocd/cluster-applications/
    git add ztp/gitops-subscriptions/argocd/policy/ ztp/gitops-subscriptions/argocd/policy-applications/
    git commit -a -m "Add du-upgrade.yaml"
    git push origin-gogs
