---
# Download the OpenShift image and upload into OpenStack Glance

- name: Create directories for cluster-deployment image
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/stack/clusterdeployments_image
    - "/home/stack/clusterdeployments_image/{{ rhacm_clusterdeploy_hub_cluster_name }}/"

- name: Check if image already exists on overcloud
  shell: |
    source /home/stack/overcloudrc
    openstack image list | grep -q "{{ rhacm_clusterdeploy_image_name }}"
  register: check_image_exists
  ignore_errors: true

- name: Download the cluster-deployment image
  get_url:
    url: "{{ rhacm_clusterdeploy_image_url }}"
    dest: "/home/stack/clusterdeployments_image/{{ rhacm_clusterdeploy_hub_cluster_name }}/{{ rhacm_clusterdeploy_image_url | basename }}"
  when: check_image_exists.failed

- name: Decompress cluster-deployment image
  shell: |
    gunzip -f "/home/stack/clusterdeployments_image/{{ rhacm_clusterdeploy_hub_cluster_name }}/{{ rhacm_clusterdeploy_image_url | basename }}"
  when: check_image_exists.failed

- name: Upload cluster-deployment image to Glance
  shell: |
    source /home/stack/overcloudrc
    openstack image create --public --disk-format qcow2 --container-format bare --file /home/stack/clusterdeployments_image/{{ rhacm_clusterdeploy_hub_cluster_name }}/{{ rhacm_clusterdeploy_image_url | basename | splitext | first }} {{ rhacm_clusterdeploy_image_name }}
  when: check_image_exists.failed
