---
# Openshift Virtualization channel
osv_channel: stable

# AMQ subscription channel
amq_channel: stable

# Cluster Logging Operator channel
cluster_logging_channel: 5.0

# Elasticsearch Operator channel
elasticsearch_channel: 5.0

# Performance Time Protocol Operator channel
ptp_channel: stable

# SR-IOV operator channel 
sriov_channel: 4.7

# Performance add-on operator 
pao_channel: 4.7

# Local Storage operator channel
lso_channel: 4.7

# To enable nightly catalog source
nightly_operator: false

brew_reg_password: ""

iib_id:
#  sriov: 25944   #openshift-sriov-network-operator
#  osv: 26761     #openshift-virtualization 
#  clo: 26761     #cluster-logging-operator
#  amq: 26761     #amq-operator
#  pao: 61726     #performance-addon-operator
#  eso: 26761     #elastic-search-operator
