---
apiVersion: v1
kind: Namespace
metadata:
  annontations:
    openshift.io/node-selector: ''
  name: assisted-installer-2
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: assisted-installer
  namespace: assisted-installer-2
spec:
  targetNamespaces:
  - assisted-installer-2
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/assisted-service-operator.assisted-installer: ""
  name: assisted-service-operator
  namespace: assisted-installer-2
spec:
  channel: alpha
  config:
    env:
    - name: OPENSHIFT_VERSIONS
      value: '{"4.8":{"display_name":"4.8.0-fc.0","release_image":"quay.io/openshift-release-dev/ocp-release:4.8.0-fc.0-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso","rhcos_version":"47.83.202102090044-0","support_level":"beta"}}'
    - name: INSTALLER_IMAGE
      value: quay.io/ocpmetal/assisted-installer:latest
    - name: SERVICE_IMAGE
      value: quay.io/ocpmetal/assisted-service:latest
    - name: DATABASE_IMAGE
      value: quay.io/ocpmetal/postgresql-12-centos7:latest
    - name: AGENT_IMAGE
      value: quay.io/ocpmetal/assisted-installer-agent:latest
    - name: CONTROLLER_IMAGE
      value: quay.io/ocpmetal/assisted-installer-controller:latest
  installPlanApproval: Automatic
  name: assisted-service-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: assisted-service-operator.v0.0.2
