---
# default vars for rhacm-ztp-platform-upgrade-setup

http_store_path: /opt/http_store

du_upgrade_channel: "fast-4.10"

du_upgrade_version: "4.10.28"

# For precaching you will want a small sno count per cgu
# Without precaching, we can support many more snos per cgu
snos_per_cgu: 5000

platform_upgrade_precache: false
platform_upgrade_concurrency: 200
platform_upgrade_timeout: 720
