- name: Create OSV hyperconverged operator
  k8s:
    state: present
    definition: "{{ lookup('template', 'kubevirt-hyperconverged.yml.j2' ) }}"

- include_role:
    name: operators
    tasks_from: 99_csv_status.yml
  vars:
    namespace: "{{ item }}"
  with_items:
    - openshift-cnv

- name: Set hostpath-provisioner as default storage class for CDI
  shell: |
    oc patch cdiconfig config --patch '{"spec": {"config": {"scratchSpaceStorageClass": "hostpath-provisioner"}}}' --type merge
  register: cdi_updating
  retries: 3 # 3 minutes
  delay: 60
  until: cdi_updating is success

- name: Configure hostpath-provisioner
  k8s:
    state: present
    definition: "{{ lookup('template', 'hostpath-prov.yaml.j2') }}"
  register: hpp
