---
# rhacm-ztp-complete-upgrade-setup tasks

- name: Create directories for rhacm-ztp
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ http_store_path }}/data/upgrade"
  - "{{ rhacm_install_directory }}/rhacm-ztp"
  - "{{ rhacm_install_directory }}/rhacm-ztp/upgrade"

# View Upgrade graphs
# https://access.redhat.com/labs/ocpupgradegraph
- name: Download upgrade graphs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ http_store_path }}/data/upgrade/{{ item.name }}"
  loop:
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.9
    name: upgrade-graph_stable-4.9
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.10
    name: upgrade-graph_stable-4.10
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.11
    name: upgrade-graph_stable-4.11
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.10
    name: upgrade-graph_fast-4.10
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.11
    name: upgrade-graph_fast-4.11
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.11
    name: upgrade-graph_candidate-4.11
  - url: https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.12
    name: upgrade-graph_fast-4.12

- name: Get list of clusters for upgrade
  shell: |
    KUBECONFIG={{ hub_cluster_kubeconfig }} oc get managedclusters -l {{ clusters_label }} --no-headers -o custom-columns=NAME:'.metadata.name'
  register: ztp_done_clusters

- name: Template CGU object(s)
  template:
    src: cgu-complete-upgrade.yml.j2
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/cgu-complete-upgrade-{{ du_upgrade_version | replace('.', '-') }}-{{ '%04d' | format(item) }}.yml"
  loop: "{{ range(((ztp_done_clusters.stdout_lines | length) / snos_per_cgu) | round(0, 'ceil') | int) | list }}"

- name: Template CGU apply/patch scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0744"
  loop:
  - src: apply-cgu-complete.sh
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/apply-cgu-complete-{{ du_upgrade_version | replace('.', '-') }}.sh"
  - src: patch-cgu-complete.sh
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/patch-cgu-complete-{{ du_upgrade_version | replace('.', '-') }}.sh"

- name: Template the gen_checksum.sh script
  template:
    src: gen_checksum.sh
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/gen_checksum.sh"
    mode: 0744

- name: Run the generate checksum script
  shell: |
    cd {{ rhacm_install_directory }}/rhacm-ztp/upgrade
    {{ rhacm_install_directory }}/rhacm-ztp/upgrade/gen_checksum.sh

- name: Get generate checksum script output
  slurp:
    src: "{{ rhacm_install_directory }}/rhacm-ztp/upgrade/checksum-{{ du_upgrade_version }}.yaml"
  register: image_signature_data

- name: Template the platform upgrade PGT and 4.12 admin-ack
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: du-upgrade.yaml.j2
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/du-upgrade.yaml"
  - src: admin-ack-4_12.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/source-crs/admin-ack-4_12.yaml"

- name: Enable platform upgrade PGT in the kustomization.yaml file
  replace:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/kustomization.yaml"
    replace: "- du-upgrade.yaml"
    regexp: "# - du-upgrade.yaml"

- name: Replace PAO configuration from original common-ranGen.yaml
  replace:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/common-ranGen.yaml"
    replace: |-
      # Start PAO
          - fileName: PaoSubscription.yaml
            policyName: "subscriptions-policy"
            complianceType: mustnothave
            spec:
              source: {{ common_catalogsource_name }}
            # Changing the channel value will upgrade/downgrade the operator installed version.
              channel: "4.10"
          - fileName: PaoSubscriptionNS.yaml
            policyName: "subscriptions-policy"
            complianceType: mustnothave
          - fileName: PaoSubscriptionOperGroup.yaml
            policyName: "subscriptions-policy"
            complianceType: mustnothave
          # - fileName: PaoOperatorStatus.yaml
          #   policyName: "subscriptions-policy"
          #   complianceType: mustnothave
      # End PAO
    regexp: '^# Start PAO[\s\S]*# End PAO'
  when: original_disconnected_operator_index_tag == "v4.10"

- name: Replace catalogsource image configuration in common-ranGen.yaml
  replace:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/common-ranGen.yaml"
    replace: "image: {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/{{ disconnected_operator_index_name }}:{{ disconnected_operator_index_tag }}"
    regexp: "image: {{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}/{{ disconnected_operator_index_name }}:{{ original_disconnected_operator_index_tag }}"

- name: Replace catalogsource name in common-ranGen.yaml
  replace:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/common-ranGen.yaml"
    replace: "{{ common_catalogsource_name }}"
    regexp: "{{ original_common_catalogsource_name }}"
  when: replace_catalogsource

- name: Append removing old catalogsource in common-ranGen.yaml
  blockinfile:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/common-ranGen.yaml"
    block: |
      # Remove the old catalogsource
          - fileName: DefaultCatsrc.yaml
            policyName: "config-policy"
            complianceType: mustnothave
            metadata:
              name: {{ original_common_catalogsource_name }}
    insertafter: "EOF"
    marker: "# {mark} {{ original_common_catalogsource_name }} removal"
  when: replace_catalogsource

- name: Commit and push the above changes to cnf-features-deploy
  shell: |
    cd {{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy
    git add ztp/gitops-subscriptions/argocd/cluster/ ztp/gitops-subscriptions/argocd/cluster-applications/
    git add ztp/gitops-subscriptions/argocd/policy/ ztp/gitops-subscriptions/argocd/policy-applications/
    git commit -a -m "Setup Complete Upgrade to {{ du_upgrade_version }}"
    git push origin-gogs
