---
- name: Enable custom registry for nightly operators
  include_tasks: 10_add_catalogsource.yml
  when:
    - build == "dev"
    - nightly_operator

- name: Install Operators
  k8s:
    state: present
    definition: "{{ lookup('template', item + '.yml.j2') }}"
  with_items:
    - performance-add-on-operator
    - sriov-network-operator
    - openshift-virtualization-operator
    - cluster-logging-operator
    - kafka-operator

- include_tasks: 99_csv_status.yml
  vars:
    namespace: "{{ item }}"
  with_items:
    - openshift-performance-addon
    - openshift-sriov-network-operator
    - openshift-cnv
    - openshift-logging
    - amq

- name: set operator facts
  set_fact:
    osv_channel: "{{ osv_channel }}"

- name: Create OSV hyperconverged operator
  k8s:
    state: present
    definition: "{{ lookup('template', 'kubevirt-hyperconverged.yml.j2' ) }}"

- name: Create Cluster logging instance
  k8s:
    state: present
    definition: "{{ lookup('file', 'cluster-logging-instance.yml' ) }}"

# Takes few seconds to initiate installation
- name: Wait for few seconds before checking for status
  wait_for:
    timeout: 10

- include_tasks: 99_csv_status.yml
  vars:
    namespace: "{{ item }}"
  with_items:
    - openshift-cnv
    - openshift-logging
