---
- name: Enable custom registry for nightly operators
  include_tasks: 10_add_catalogsource.yml
  when:
    - nightly_operator

- name: Install Operators
  k8s:
    state: present
    definition: "{{ lookup('template', item.name + '.yml.j2') }}"
  with_items: "{{ operators }}"

- include_tasks: 99_csv_status.yml
  vars:
    namespace: "{{ item.namespace }}"
  with_items: "{{ operators }}"

- name: CNV related tasks
  block:
    - name: set operator facts
      set_fact:
        osv_channel: "{{ osv_channel }}"
  when: operators | selectattr('namespace', 'search', 'openshift-cnv') | list | length > 0

- name: CLuster Logging Instance
  k8s:
    state: present
    definition: "{{ lookup('file', 'cluster-logging-instance.yml' ) }}"
  tags: logging

- name: Download and unarchive kube-burner
  unarchive:
    src: "https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.13.2/kube-burner-0.13.2-Linux-x86_64.tar.gz"
    dest: /usr/bin/
    remote_src: yes
    mode: 0700
  become: true
