---
- name: Install Operators
  k8s:
    state: present
    definition: "{{ lookup('template', item + '.yml.j2') }}"
  with_items:
    - performance-add-on-operator
    - sriov-network-operator
    - openshift-virtualization-operator

- name: Check PAO operator version
  shell: |      
      oc get csv -n openshift-performance-addon --no-headers | awk '{print $1}'
  register: pao_version

- name: Check PAO operator status
  shell: |
    oc get csv -n openshift-performance-addon {{ pao_version.stdout }} --template={{'{{'}}.status.phase{{'}}'}}
  register: pao_status
  retries: 3 # 3 minutes
  delay: 60
  until: pao_status.stdout == "Succeeded"
  changed_when: pao_status.stdout == "Succeeded"

- name: Check SRIOV operator version
  shell: |      
      oc get csv -n openshift-sriov-network-operator  --no-headers | awk '{print $1}'
  register: sriov_version

- name: Check SRIOV operator status
  shell: |
    oc get csv -n openshift-sriov-network-operator {{ sriov_version.stdout }} --template={{'{{'}}.status.phase{{'}}'}}
  register: sriov_status
  retries: 5 # 5 minutes
  delay: 60
  until: sriov_status.stdout == "Succeeded"
  changed_when: sriov_status.stdout == "Succeeded"

- name: Check OSV operator version
  shell: |      
      oc get csv -n openshift-cnv --no-headers | awk '{print $1}'
  register: osv_version

- name: Check OSV operator status
  shell: |
    oc get csv -n openshift-cnv {{ osv_version.stdout }} --template={{'{{'}}.status.phase{{'}}'}}
  register: osv_status
  retries: 5 # 5 minutes
  delay: 60
  until: osv_status.stdout == "Succeeded"
  changed_when: osv_status.stdout == "Succeeded"      

- name: Create OSV hyperconverged operator
  k8s:
    state: present
    definition: "{{ lookup('file', 'kubevirt-hyperconverged.yml' ) }}"

- name: Check OSV operator status again
  shell: |
    oc get csv -n openshift-cnv {{ osv_version.stdout }} --template={{'{{'}}.status.phase{{'}}'}}
  register: osv_status
  retries: 5 # 5 minutes
  delay: 60
  until: osv_status.stdout == "Succeeded"
  changed_when: osv_status.stdout == "Succeeded"
