---

- name: Create k3d Cluster
  shell: |
    k3d cluster list | grep k3d-{{ item }} || k3d cluster create k3d-{{ item }}
  register: output

- name: Debug the create output
  debug:
    msg: "{{ output }}"
