---
# default vars for rhacm-ztp-complete-upgrade-setup

http_store_path: /opt/http_store

clusters_label: "ztp-done="

du_upgrade_channel: "fast-4.12"

du_upgrade_version: "4.12.1"

# For 4.11 to 4.12 Y-stream upgrade an admin ack is required to permit the upgrade
include_admin_ack: true

disconnected_operator_index_name: olm-mirror/redhat-operator-index
disconnected_operator_index_tag: v4.12

# Must match the original used in common-ranGen.yaml PGT
original_disconnected_operator_index_tag: v4.11

# Must match the original used in common-ranGen.yaml PGT
common_catalogsource_name: rh-du-operators

snos_per_cgu: 1000

complete_upgrade_backup: false
complete_upgrade_precache: false
complete_upgrade_concurrency: 1000
# 180 = 3 hours
complete_upgrade_timeout: 180
complete_upgrade_enable: false

# Amount of time to sleep between applying CGUs for upgrade (that are not enabled)
# Allows offsetting of the backup and precache steps before an actual upgrade
complete_upgrade_apply_sleep: 180
complete_upgrade_patch_sleep: 180

# Extra minutes between timeout of complete upgrade CGUs during either apply or patch scripts
complete_upgrade_apply_offset: 0
complete_upgrade_patch_offset: 30
