---
# default vars for rhacm-ztp-complete-upgrade-setup

http_store_path: /opt/http_store

du_upgrade_channel: "fast-4.10"

du_upgrade_version: "4.10.28"

disconnected_operator_index_name: olm-mirror/redhat-operator-index
disconnected_operator_index_tag: v4.11

# Must match the original used in common-ranGen.yaml PGT
original_disconnected_operator_index_tag: v4.10

# Must match the original used in common-ranGen.yaml PGT
common_catalogsource_name: rh-du-operators

snos_per_cgu: 5000

complete_upgrade_precache: false
complete_upgrade_concurrency: 1000
# 720 = 12 hours
complete_upgrade_timeout: 720
complete_upgrade_enable: true
