- name: Create Trident CRD
  k8s:
    state: present
    definition: "{{ lookup('file', 'tridentorchestrators_crd.yaml') }}"

- name: Create Trident Operator resources and pods
  k8s:
    state: present
    definition: "{{ lookup('template', 'bundle.yaml.j2') }}"

- name: Check and wait for Trident Operator pod state
  shell: |
    oc get pods -n {{ trident_namespace }} -l app=operator.trident.netapp.io -o jsonpath='{.items[0].status.phase}'
  retries: 10
  delay: 5
  register: trident_pod
  until: trident_pod.stdout == "Running"

- name: Create Trident Controller pods
  k8s:
    state: present
    definition: "{{ lookup('template', 'tridentorchestrator_cr.yaml.j2') }}"

- name: Check and wait for Trident Controller pod state
  shell: |
    oc get pod -n {{ trident_namespace }} -l app=controller.csi.trident.netapp.io -o jsonpath='{.items[0].status.phase}'
  retries: 25
  delay: 10
  register: trident_controller_pod
  until: trident_controller_pod.stdout == "Running"

- name: Generate ONTAP Trident Backend Configuration
  template:
    src: "backend.json.j2"
    dest: "/tmp/backend.json"

- name: Get Trident Controller pod
  shell: |
    oc get pod -n {{ trident_namespace }} -l app=controller.csi.trident.netapp.io -o jsonpath='{.items[0].metadata.name}'
  register: trident_controller_pod_name

- name: Get base64 Encoding of ONTAP Backend Configuration
  shell: "sed 's/[ \t]//g' /tmp/backend.json | tr -d '\n' | base64 -w0"
  register: backend_json_base64

- name: Wait for few seconds before connecting backend
  wait_for:
    timeout: 60

- name: Create ONTAP Trident Backend
  shell: |
    oc exec -n {{ trident_namespace }} {{ trident_controller_pod_name.stdout }} -c trident-main -- tridentctl --debug --namespace {{ trident_namespace }} create backend --base64 {{ backend_json_base64.stdout }}
