---
# default vars for rhacm-ztp-setup

cnf_features_deploy_repo: https://github.com/openshift-kni/cnf-features-deploy.git
cnf_features_deploy_branch: release-4.10

gogs_host: "[fc00:1000::1]"
gogs_port: 10880
gogs_username: testadmin
gogs_password: testadmin

disconnected_operator_index_name: olm-mirror/redhat-operator-index
disconnected_operator_index_tag: v4.9
