---
# default vars for rhacm-ztp-setup

cnf_features_deploy_repo: https://github.com/openshift-kni/cnf-features-deploy.git
cnf_features_deploy_branch: release-4.11

# Pre-creates manifests for the desired number of argocd cluster applications
cluster_applications_count: 35
siteconfigs_per_application: 100

siteconfigs_directories:
- /root/hv-vm/sno/siteconfigs
- /root/hv-vm/compact/siteconfigs
- /root/hv-vm/standard/siteconfigs

gogs_host: "[fc00:1000::1]"
gogs_port: 10880
gogs_username: testadmin
gogs_password: testadmin

disconnected_operator_index_name: olm-mirror/redhat-operator-index
disconnected_operator_index_tag: v4.11

ztp_site_generator_image_tag: v4.12.1-1

# Initialize the siteconfig list so it can be sorted later
siteconfig_list: []

# Adjust the name of the du profile catalog source so it does not conflict with default names
# https://bugzilla.redhat.com/show_bug.cgi?id=2074612
common_catalogsource_name: rh-du-operators

# https://issues.redhat.com/browse/LOG-3406
# https://access.redhat.com/solutions/6990588
# Prevents CLO on SNO from crashlooping over missing CRD (Fixed in v5.6.0 of CLO)
include_clo_fix: false

# Allow the du profile PAO subscription channel to be overridden
pao_subscription_channel: "4.10"

# These policy names were adjusted to increase the number of ztp generated policies to match as if performanceprofile
# was enabled.  The original names are commented below.
group_policy_logforwarder_name: "config-log-policy"
group_policy_storage_name: "config-storage-policy"
# group_policy_logforwarder_name: "config-policy"
# group_policy_storage_name: "config-policy"
