apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 namespace: assisted-installer
 name: agent
spec:
 databaseStorage:
  accessModes:
  - ReadWriteOnce
  storageClassName: localstorage-sc
  resources:
   requests:
    storage: 20Gi
 filesystemStorage:
  accessModes:
  - ReadWriteOnce
  storageClassName: localstorage-sc
  resources:
   requests:
    storage: 100Gi
