---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assisted-service-lease
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: assisted-service-lease
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: assisted-service-lease
subjects:
- kind: ServiceAccount
  name: default
  namespace: assisted-installer
