apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
{% for sc in range((item - 1) * siteconfigs_per_application, item * siteconfigs_per_application ) %}
{% if siteconfig_list | length > sc %}
#- ./{{ siteconfig_list[sc] }}-siteconfig.yml
{% endif %}
{% endfor %}

resources:
{% for sc in range((item - 1) * siteconfigs_per_application, item * siteconfigs_per_application ) %}
{% if siteconfig_list | length > sc %}
#- ./{{ siteconfig_list[sc] }}-resources.yml
{% endif %}
{% endfor %}
