---
# Playbook to deploy the performance profile 
# 
# Example Usage:
#
# export KUBECONFIG=/home/user/kubeconfig
# time ansible-playbook -i ansible/inventory/localhost.local ansible/cnf-profile.yml
#

- name: Deploy cnf-profile
  hosts: orchestration
  roles:
    - cnf_profile
    
