---
# Playbook to label node(s) before installing/configuring things
#
# Example Usage:
#
# export KUBECONFIG=/home/user/kubeconfig
# time ansible-playbook -i ansible/inventory/hosts ansible/label-node.yml
#

- hosts: orchestration
  vars_files:
    - vars/all.yml
  pre_tasks:
    - name: run validations
      include_tasks: tasks/validation.yml
  roles:
    - label_node
