---
# Playbook to label node(s) before installing/configuring things
#
# Example Usage:
#
# export KUBECONFIG=/home/user/kubeconfig
# time ansible-playbook -i ansible/inventory/localhost.local ansible/label-node.yml
#

- name: Label nodes
  hosts: orchestration
  vars_files:
    - vars/all.yml
  roles:
    - label_node
