---
# Playbook to install MCE Build
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/cloud42.local ansible/mce-deploy.yml
#

- name: Setup downstream MCE/RHACM ICSP
  hosts: orchestration
  vars_files:
  - vars/all.yml
  roles:
  - rhacm-hub-icsp

- name: Fix ipv6/disconnected nodes /etc/containers/registries.conf for tag mirroring
  hosts: fix_icsp_nodes
  vars_files:
  - vars/all.yml
  roles:
  - icsp-enable-tag-mirror

- name: Install MCE
  hosts: orchestration
  vars_files:
  - vars/all.yml
  roles:
  - mce-deploy
  - mce-assisted-installer
  - mce-add-clusterimagesets
