---
# Playbook to install RHACM
#
# Example Usage:
#
# export KUBECONFIG=/home/user/kubeconfig
# time ansible-playbook -i ansible/inventory/localhost.local ansible/rhacm-hub-released.yml -e "rhacm_version=2.1"
#

- name: Install released version of RHACM
  hosts: orchestration
  vars_files:
    - vars/all.yml
  roles:
    - rhacm-hub-released
