---
# Playbook to prepare rhacm shiftstack hub cluster for cluster provisioning
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/undercloud.hosts ansible/rhacm-shiftstack-prepare-cluster-deployment.yml -e "rhacm_clusterdeploy_index_start=0 rhacm_clusterdeploy_index_count=3"
#

- name: Add clusterimagesets and setup to build multiple cluster-deployment configurations
  hosts: orchestration
  remote_user: stack
  vars_files:
    - vars/all.yml
  roles:
    - rhacm_get_shiftstack_cd_config
    - openstack_openshift_image
    - rhacm_add_clusterimagesets
  post_tasks:
    # In order to allow this process to be more concurrent, we leverage creating an
    # inventory host per provisioned cluster to be created
    - name: Add host for each cluster to be provisioned
      add_host:
        name: "orchestration-{{ item }}"
        group: "buildcdconfigs"
        ansible_host: "{{ inventory_hostname }}"
        rhacm_clusterdeployment_name: "{{ rhacm_clusterdeploy_prefix }}{{ item }}"
        clouds_yaml_auth_url: "{{ clouds_yaml_auth_url_content.stdout }}"
        clouds_yaml_username: "{{ clouds_yaml_username_content.stdout }}"
        clouds_yaml_password: "{{ clouds_yaml_password_content.stdout }}"
        clouds_yaml_user_domain_name: "{{ clouds_yaml_user_domain_name_content.stdout }}"
        clouds_yaml_project_name: "{{ clouds_yaml_project_name_content.stdout }}"
        clouds_yaml_project_domain_name: "{{ clouds_yaml_project_domain_name_content.stdout }}"
        ssh_public_key: "{{ ssh_pub_key_content['content'] | b64decode }}"
        ssh_private_key: "{{ ssh_private_key_content['content'] }}"
        clusterdeployment_pull_secret: "{{ cluster_pull_secret_json['data']['.dockerconfigjson'] }}"
      with_sequence: "start={{ rhacm_clusterdeploy_index_start|int }} count={{ rhacm_clusterdeploy_index_count|int }} format=%05u"

- name: Create {{ rhacm_clusterdeploy_index_count }} RHACM cluster deployment configuration(s)
  hosts: buildcdconfigs
  remote_user: stack
  vars_files:
    - vars/all.yml
  roles:
    - rhacm_build_shiftstack_cd_config

- name: Generate MCO object for hub cluster dns for cluster deployments
  hosts: orchestration
  remote_user: stack
  vars_files:
    - vars/all.yml
  roles:
    - rhacm_clusterdeployment_coredns
    - rhacm_clusterdeployment_test
