---
# Playbook to install RHACM Assisted Installer and prepare for clusterdeployments
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/cloud-root.local ansible/rhacm-assisted-installer.yml
#
# ipv6/disconnected example run:
# time ansible-playbook -i ansible/inventory/cloud03-root.local ansible/rhacm-assisted-installer.yml -e 'http_store_host="[fc00:1000::1]"'
#

- name: Install RHACM Assisted Installer
  hosts: orchestration
  vars_files:
    - vars/all.yml
  roles:
    - rhacm-assisted-installer
    - rhacm_add_clusterimagesets
