---
# Playbook to install RHACM Upstream/Downstream Build
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/undercloud.hosts ansible/rhacm-hub-deploy.yml
#

- name: Install downstream RHACM
  hosts: orchestration
  vars_files:
    - vars/all.yml
  roles:
    - rhacm-hub-deploy
