---
# Playbook to install RHACM Downstream Build
#
# Example Usage:
#
# time ansible-playbook -i ansible/inventory/undercloud.hosts ansible/rhacm-hub-downstream.yml
#

- name: Install downstream RHACM
  hosts: orchestration
  remote_user: stack
  vars_files:
    - vars/all.yml
  roles:
    - rhacm_hub_downstream
