---
# rhacm-ztp-setup tasks

- name: Clear old cnf-features-deploy clone
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy"

- name: Create directories for rhacm-ztp
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ rhacm_install_directory }}/rhacm-ztp"
  - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy"

- name: Clone cnf-features-deploy
  git:
    repo: "{{ cnf_features_deploy_repo }}"
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy"
    force: true
    version: "{{ cnf_features_deploy_branch }}"

# Perhaps we can detect if the repo exists already instead of ignoring errors
- name: Create cnf-features-deploy repo in gogs
  uri:
    url: "http://{{ gogs_host }}:{{ gogs_port }}/api/v1/admin/users/{{ gogs_username }}/repos"
    user: "{{ gogs_username }}"
    password: "{{ gogs_password }}"
    force_basic_auth: true
    method: POST
    headers:
      content-type: application/json
      Accept: application/json
    body: {"name": "cnf-features-deploy", "description": "test repo", "private": false}
    body_format: json
    validate_certs: no
    status_code: 201
    return_content: yes
  ignore_errors: true

# The --force flag on the git push forces the gogs fork of the repo to be reset to the above "clone"
- name: Push cnf-features-deploy into gogs
  shell: |
    cd {{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy
    git remote add origin-gogs http://{{ gogs_username }}:{{ gogs_password }}@{{ gogs_host }}:{{ gogs_port }}/testadmin/cnf-features-deploy.git
    git push -u origin-gogs --all --force

- name: Patches for cnf-features-deploy argocd-openshift-gitops-patch.json
  replace:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json"
    replace: "{{ item.replace }}"
    regexp: "{{ item.regexp }}"
  loop:
  - replace: "{{ rhacm_disconnected_registry }}"
    regexp: "quay.io"
  - replace: "openshift-kni"
    regexp: "redhat_emp1"

- name: Remove the examples/siteconfig directory from cnf-features-deploy
  file:
    state: absent
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/example/siteconfig"

- name: Remove the cluster/policies app from cnf-features-deploy argocd deployment
  file:
    state: absent
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/deployment/{{ item }}"
  loop:
  - clusters-app.yaml
  - policies-app.yaml

- name: Remove clusters-app.yaml and policies-app.yaml from cnf-features-deploy argocd deployment kustomization.yaml
  replace:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/deployment/kustomization.yaml"
    replace: ""
    regexp: "{{ item }}"
  loop:
  - ".*- clusters-app.yaml"
  - ".*- policies-app.yaml"

- name: Create cluster and policy directories in cnf-features-deploy
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster/"
  - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster-applications/"
  - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/"
  - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/"
  - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy-applications/"

- name: Create cluster application directories in cnf-features-deploy
  file:
    path: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster/cluster-{{ '%02d' | format(item) }}"
    state: directory
  loop: "{{ range(1, cluster_applications_count + 1) | list }}"

- name: Copy siteconfigs
  copy:
    src: "{{ siteconfigs_directory }}"
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster/"
    remote_src: true

- name: Get siteconfig manifest names
  find:
    paths:
    - "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster/siteconfigs"
    use_regex: true
    patterns: ['.*.yml']
  register: siteconfigs_find

- name: Set siteconfig list
  set_fact:
    siteconfig_list: "{{ siteconfig_list + [item.path | basename] }}"
  loop: "{{ siteconfigs_find.files }}"

- name: Sort siteconfig list
  set_fact:
    siteconfig_list: "{{ siteconfig_list | sort }}"

- name: Create cluster kustomization files in cnf-features-deploy
  template:
    src: cluster-kustomization.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster/cluster-{{ '%02d' | format(item) }}/kustomization.yaml"
  loop: "{{ range(1, cluster_applications_count + 1) | list }}"

# Similiar to the above kustomization file template, every cluster app's directoy must contain the actual siteconfig and not just a relative path "down" to the resource
- name: Loop through copying correct siteconfigs into each cluster application directory
  shell: |
    {% for sc in range((item - 1) * siteconfigs_per_application, item * siteconfigs_per_application ) %}
    {% if siteconfig_list | length > sc %}
    cp {{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster/siteconfigs/{{ siteconfig_list[sc] | basename }} {{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster/cluster-{{ '%02d' | format(item) }}/{{ siteconfig_list[sc] | basename }}
    {% endif %}
    {% endfor %}
  loop: "{{ range(1, cluster_applications_count + 1) | list }}"
  when: siteconfig_list | length > ((item - 1) * siteconfigs_per_application)

- name: Create cluster application files in cnf-features-deploy
  template:
    src: cluster-ns-application.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/cluster-applications/cluster-{{ '%02d' | format(item) }}.yaml"
  loop: "{{ range(1, cluster_applications_count + 1) | list }}"

- name: Get mirrored operator index ImageContentSourcePolicy to append to common-ranGen.yaml
  shell: |
    cat {{ mirrored_operator_icsp }} | awk '/repositoryDigestMirrors:/,/END_OF_FILE/'
  register: icsp_digest_mirrors

- name: Template the policy manifests into cnf-features-deploy
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: common-ranGen.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/common-ranGen.yaml"
  - src: group-du-sno-ranGen.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/group-du-sno-ranGen.yaml"
  - src: group-du-sno-validator-ranGen.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/group-du-sno-validator-ranGen.yaml"
  - src: policy-kustomization.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/kustomization.yaml"
  - src: ns.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy/common-and-group/ns.yaml"
  - src: policy-common-and-group.yaml
    dest: "{{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy/ztp/gitops-subscriptions/argocd/policy-applications/common-and-group.yaml"

- name: Commit and push the above changes to cnf-features-deploy
  shell: |
    cd {{ rhacm_install_directory }}/rhacm-ztp/cnf-features-deploy
    git add ztp/gitops-subscriptions/argocd/cluster/ ztp/gitops-subscriptions/argocd/cluster-applications/
    git add ztp/gitops-subscriptions/argocd/policy/ ztp/gitops-subscriptions/argocd/policy-applications/
    git commit -a -m "Remove example clusters, add siteconfigs, add argocd cluster applications, and add common and group policies"
    git push origin-gogs
