apiVersion: batch/v1
kind: Job
metadata:
  name: infra-consumer
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: infra-consumer
        image: registry.redhat.io/amq7/amq-streams-kafka-27-rhel7:1.7.0
        command: ["bin/kafka-console-consumer.sh","--bootstrap-server", "my-cluster-kafka-bootstrap:9092", "--topic", "topic-logging-infra", "--group", "infra-consumer", "--from-beginning"]
      restartPolicy: Never
