apiVersion: batch/v1
kind: Job
metadata:
  name: alerts-consumer
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: alerts-consumer
        image: "registry.redhat.io/amq7/amq-streams-kafka-25-rhel7@sha256:e719f662bd4d6b8c54b1ee2e47c51f8d75a27a238a51d9ee38007187b3a627a4"
        command: ["bin/kafka-console-consumer.sh","--bootstrap-server", "my-cluster-kafka-bootstrap:9092", "--topic", "topic-logging-alerts", "--group", "alerts-consumer", "--from-beginning"]
      restartPolicy: Never

