apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kafka-minion
  name: kafka-minion
  namespace: amq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-minion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-minion
    spec:
      containers:
        - image: quay.io/google-cloud-tools/kafka-minion:v1.0.2                                                   
          name: kafka-minion
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          env:
          - name: KAFKA_BROKERS
            value: my-cluster-kafka-bootstrap.amq.svc:9093                                                        
          - name: KAFKA_TLS_ENABLED
            value: "true"
    replicas: 1
