---
# rhacm-hub-deploy default vars

rhacm_deploy_repo: https://github.com/stolostron/deploy.git
rhacm_deploy_repo_branch: master

rhacm_observability_storageclass: localstorage-sc

observability_alertmanagerStorageSize: 1Gi
observability_compactStorageSize: 100Gi
observability_receiveStorageSize: 100Gi
observability_ruleStorageSize: 1Gi
observability_storeStorageSize: 10Gi
